### ISSUE TITLE
servo

### ISSUE THREAD

**Issue by Ahmad-Needs-Help** [thewhiteh4t/seeker#289] opened 2021-05-17 18:19 UTC
servo is always offline for some reason and it never goes online
 
 - OS: [Android]
 - OS Version [7.1.2]
 - Browser [Chrome/Tor]
 - Full Browser Version [idk]

**Comment by thewhiteh4t** [comment] 2021-05-17 18:31
Duplicate of #282

**Closed by thewhiteh4t** 2021-05-17 18:31 UTC
