### ISSUE TITLE
Seeker installation 

### ISSUE THREAD

**Issue by Vivekhacker12** [thewhiteh4t/seeker#504] opened 2024-05-29 06:04 UTC
[!] Installing Dependencies...

python - Installed
php - Installed
requests - Installed
packaging - Installed
psutil - Failed!
![Screenshot_20240529-113424_Termux](https://github.com/thewhiteh4t/seeker/assets/170487082/84fdbc51-ffcb-42dc-9750-79be35929de0)

**Comment by thewhiteh4t** [comment] 2024-05-29 07:44
duplicate of https://github.com/thewhiteh4t/seeker/issues/499

closing.

**Closed** 2024-05-29 07:44 UTC
