### ISSUE TITLE
Locally built, without ngrok, why can't I access it, is it because of ssl? How to solve it

### ISSUE THREAD

**Issue by cxaqhq** [thewhiteh4t/seeker#160] opened 2020-03-25 12:57 UTC
Can't access without ssl?

**Comment by thewhiteh4t** [comment] 2020-03-25 13:03
@cxaqhq yes you cannot access without ssl because as per html api if the site is not secure, it will not ask for location permission, so ssl is necessary

**Comment by thewhiteh4t** [comment] 2020-03-25 13:21
Duplicate of https://github.com/thewhiteh4t/seeker/issues/159

**Closed by thewhiteh4t** 2020-03-25 13:21 UTC
Labels: duplicate
