### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by dhanushkkarh** [thewhiteh4t/seeker#337] opened 2021-12-27 11:49 UTC
Hi, IM currently running on Kali Linux. All the dependencies are up to date. I get the following error while running seeker.py
`/  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \                                
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/                                
/____  > \___  >\___  >|__|_ \ \___  >|__|                                   
         \/      \/     \/      \/     \/                                    

[>] Created By : thewhiteh4t
[>] Version    : 1.2.5

[+] Checking for Updates.....[ Up-To-Date ]
                                                                             
[+] Checking Serveo Status...[ Offline ]`

After showing this, the program automatically goes back to the directories list screen. 
Help is appreciated

**Comment by sansanmhmd10** [comment] 2022-01-02 02:54
> Hai, IM saat ini berjalan di Kali Linux. Semua dependensi terbaru. Saya mendapatkan kesalahan berikut saat menjalankan seeker.py `/ ___/_ / __ _/ __ \ | |/ /_ / __ \_ __ \ ___ \ \ _**/\ **_/ | < \ _**/ | | / /**__ > _** >_** >| __|_ \ __ _ >|__| / / / / /
> 
> [>] Dibuat Oleh : thewhiteh4t [>] Versi : 1.2.5
> 
> [+] Memeriksa Pembaruan.....[ Terkini ]
> 
> [+] Memeriksa Status Server...[ Offline ]`
> 
> Setelah menunjukkan ini, program secara otomatis kembali ke layar daftar direktori. Bantuan dihargai

how to solve it, if serveo is offline?

**Comment by thewhiteh4t** [comment] 2022-01-03 00:34
@dhanushkkarh @sansanmhmd10 
duplicate of https://github.com/thewhiteh4t/seeker/issues/282

**Closed by thewhiteh4t** 2022-01-03 00:34 UTC
