### ISSUE TITLE
Installing dependencies is failing 

### ISSUE THREAD

**Issue by D-BayyaReddy** [thewhiteh4t/seeker#489] opened 2023-12-21 05:44 UTC
**Describe the Error / Feature Request**
chmod +x install.sh
$ ./install.sh
[!] Installing Dependencies...

python - Failed!
php - Failed!
requests - Failed!
packaging - Failed!
psutil - Failed!
---

**To Reproduce**

---

**Expected behavior**

---

**Screenshots**

---

**Please complete the following information :**
 
 - OS:
 - OS Version:
 - Browser:
 - Full Browser Version:

**Comment by thewhiteh4t** [comment] 2023-12-21 05:47
duplicate of https://github.com/thewhiteh4t/seeker/issues/482

**Closed** 2023-12-21 05:47 UTC
