### ISSUE TITLE
Use with your own domain

### ISSUE THREAD

**Issue by Pepepy** [thewhiteh4t/seeker#502] opened 2024-05-20 12:14 UTC
Hello everyone.
Does anyone know how the application could be installed with its own domain or server? without using NGROK. How could I redirect the requests through my text.com domain hosted on my server xxx.xxx.xxx.xxx, so as not to depend on the tunnels to ngrok and so that the generated url is more real.

**Comment by thewhiteh4t** [comment] 2024-05-20 12:29
duplicate of https://github.com/thewhiteh4t/seeker/issues/436

**Closed** 2024-05-20 12:29 UTC
