### ISSUE TITLE
Install failed 

### ISSUE THREAD

**Issue by dragon12345678910** [thewhiteh4t/seeker#484] opened 2023-11-05 17:09 UTC
**Describe the Error / Feature Request**
Python3 - Installed
PHP - Installed
Requests - Failed!
Packaging - Failed!
Psutil - Failed!
![IMG_20231105_180818](https://github.com/thewhiteh4t/seeker/assets/72302797/a7411bb0-104b-4c64-b85d-fa07e17f61f7)

**Comment by thewhiteh4t** [comment] 2023-11-05 17:32
duplicate of https://github.com/thewhiteh4t/seeker/issues/482

look for existing issues before creating duplicates, closing.

**Closed by thewhiteh4t** 2023-11-05 17:32 UTC

**Comment by dragon12345678910** [comment] 2023-11-06 12:02
> duplicate of #482
> 
> look for existing issues before creating duplicates, closing.

Ok , ty
