### ISSUE TITLE
Error seeker.py

### ISSUE THREAD

**Issue by dx3ham** [thewhiteh4t/seeker#179] opened 2020-04-20 22:13 UTC
Hello friend, im pleased to say hello, i have a syntax error when executing the seeker.py file, i was searching and i dint found what it is, the error is:
File "seeker.py", line 49
    print (G + '[+]' + C + 'Checking for Updates.....' , end='')
                                                                                     ^
SyntaxError: invalid syntax

i hope you can help me.
Thanks and regards.

**Comment by thewhiteh4t** [comment] 2020-04-21 19:46
Duplicate of #120

**Closed by thewhiteh4t** 2020-04-21 19:46 UTC
Labels: duplicate
