### ISSUE TITLE
Serveo Status Offline

### ISSUE THREAD

**Issue by GigaHertzLegacy-SpiderX** [thewhiteh4t/seeker#326] opened 2021-11-06 08:08 UTC
[+] Checking Serveo Status...[ Offline ]

[-] facing this issue, how to fix it ?

**Comment by thewhiteh4t** [comment] 2021-11-08 02:45
duplicate of https://github.com/thewhiteh4t/seeker/issues/282
closing.

**Closed by thewhiteh4t** 2021-11-08 02:45 UTC
