### ISSUE TITLE
Can't send back the information after visiting the website, how to solve it

### ISSUE THREAD

**Issue by toygang** [thewhiteh4t/seeker#149] opened 2020-02-19 07:11 UTC
![image](https://user-images.githubusercontent.com/38432294/74810245-f062e900-5329-11ea-9c41-e71facee7975.png)

**Comment by thewhiteh4t** [comment] 2020-02-19 07:21
Duplicate of https://github.com/thewhiteh4t/seeker/issues/148 
Closing.

**Closed by thewhiteh4t** 2020-02-19 07:21 UTC
Labels: duplicate
